# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8301dabbbad36df6c2964b977450c07bb293840ad49048269353a117698c7b3b41b3f4b377d14cc9bbc5d6645d6cfbd31e0fc63cca64269720d2b4eeffe47563

test:
  secret_key_base: 901d273a6615d699668adf45731bf64205d100f79c82843dbe4d16ec335b8f433c02f70af4e6eb2202b2ed94081248bbd145f4cdfa762d051c406db923ca3861

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
